[template]
prefix = "/traffics.de"
src = "nginx.conf.tmpl"
dest = "/etc/nginx/nginx.conf"
keys = [
    "/hello-world-expressjs-docker",
]
check_cmd = "nginx -t -c {{.src}}"
reload_cmd = "nginx -s reload"
